server:
  host: localhost
  port: 12320
storage:
  root: '/tmp'
  path: 'uploads/%y/%m/%d'
  filename: '%name.%ext'
  fileMaxSize: 100 #5242880 # 5 megabytes
serve:
  # Serve images via fileserver itself.
  # Turn off to serve images via web-server like Nginx.
  enabled: true
  url: 'http://lvh.me:12320'
