server:
  host: localhost
  port: 12320
storage:
  root: '/tmp'
  path: 'uploads/%y/%m/%d'
  filename: '%name.%ext'
  fileMaxSize: 5242880 # 5 megabytes
serve:
  # Serve images via fileserver itself.
  # Note: Better use Nginx for that on production.
  url: 'http://lvh.me:12320'
