server:
  host: 'localhost'
  port: '9001'
file:
  fieldName: 'file'
  maxSize: 100 # bytes
storage:
  root: '/tmp'
  path: 'uploads/%y/%m/%d'
  filename: '%name.%ext'
  url: 'http://uploads.easywygdev.com'
  xSendfileEnabled: true
  xSendfileHeader: 'X-Accel-Redirect' # or X-Sendfile
routes:
  upload: '/upload'
  copy: '/copy'
