server:
  host: 'localhost'
  port: '9001'
file:
  fieldName: 'file'
  maxSize: 1000000 # bytes
storage:
  root: '/media/tanraya/sandbox/commercial/easywyg/easywyg-fileserver'
  path: 'uploads/%y/%m/%d'
  filename: '%name.%ext'
  url: 'http://localhost:9001'
  xSendfileEnabled: true
  xSendfileHeader: 'X-Accel-Reirect' # or X-Sendfile
routes:
  upload: '/upload'
  copy: '/copy'
