#!/bin/sh

USER="username"
NODE_ENV="production"
CONFIG="/somewhere/on/filesystem/config.yml"
PID_FILE="/var/log/easywyg-fileserver.pid"
LOG_FILE="/run/easywyg-fileserver.log"

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: easywyg-fileserver is the script for starting a easywyg-fileserver on boot.
### BEGIN INIT INFO
# Provides:          easywyg-fileserver
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop node
# Description: easywyg-fileserver process
### END INIT INFO

###############

USAGE="Usage: $0 {start|stop|restart|status} [--force]"
FORCE_OP=false

pid_file_exists() {
    [ -f "$PID_FILE" ]
}

get_pid() {
    echo "$(cat "$PID_FILE")"
}

is_running() {
    PID=$(get_pid)
    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
}

start_it() {
    echo "Starting easywyg-fileserver ..."
    echo "(NODE_ENV=$NODE_ENV easywyg-fileserver --config $CONFIG 1>$LOG_FILE 2>&1 & echo \$! > $PID_FILE)" | sudo -i -u $USER
    echo "easywyg-fileserver started with pid $(get_pid)"
}

stop_process() {
    PID=$(get_pid)
    echo "Killing process $PID"
    kill $PID
}

remove_pid_file() {
    echo "Removing pid file"
    rm -f "$PID_FILE"
}

start_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "easywyg-fileserver already running with pid $PID"
            exit 1
        else
            echo "easywyg-fileserver stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "Forcing start anyways"
                remove_pid_file
                start_it
            fi
        fi
    else
        start_it
    fi
}

stop_app() {
    if pid_file_exists
    then
        if is_running
        then
            echo "Stopping easywyg-fileserver ..."
            stop_process
            remove_pid_file
            echo "easywyg-fileserver stopped"
        else
            echo "easywyg-fileserver already stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "Forcing stop anyways ..."
                remove_pid_file
                echo "easywyg-fileserver stopped"
            else
                exit 1
            fi
        fi
    else
        echo "easywyg-fileserver already stopped, pid file does not exist"
        exit 1
    fi
}

status_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "easywyg-fileserver running with pid $PID"
        else
            echo "easywyg-fileserver stopped, but pid file exists"
        fi
    else
        echo "easywyg-fileserver stopped"
    fi
}

case "$2" in
    --force)
        FORCE_OP=true
    ;;

    "")
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        status_app
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac
